"""
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
"""

def main():
    fibo = fibonacci(4000000)
    fibo_even = filter(even_filter, fibo)
    print(sum(fibo_even))

def even_filter(x):
    if x%2 == 0:
        return True
    else:
        return False

def fibonacci(limit):
    """Generate all fibonacci numbers upto limit
    """
    fibo = []
    fibo.append(1)
    fibo.append(2)

    while fibo[-1] < limit:
        fibo.append(fibo[-1] + fibo[-2])

    return fibo


if __name__ == '__main__':
    main()